const DEFAULT_USERS={
"1000234567890":{pass:"demo1234",name:"Amanuel Tesfaye",balance:84750.55,email:"amanuel.demo@example.test",phone:"+251 900 000 001",transactions:[["2026-09-14","Salary Credit",32500],["2026-09-12","Supermarket",-1245.40],["2026-09-08","Mobile Payment",-650],["2026-09-01","Transfer received",8000],["2026-08-27","Utility bill",-1180.25]]},
"1000325476908":{pass:"1234good",name:"Yeabsira Abrham",balance:105001.15,email:"yeabsira.demo@example.test",phone:"+251 900 000 002",transactions:[["2026-09-13","Transfer received",15000],["2026-09-11","Restaurant",-860],["2026-09-05","Salary Credit",42000],["2026-08-29","Online purchase",-2150.50],["2026-08-24","Cash deposit",10000]]},
"1000043658711":{pass:"ilovejesus",name:"Yosef Yohannes",balance:1004560.31,email:"yosef.demo@example.test",phone:"+251 900 000 003",transactions:[["2026-09-14","Business payment",75000],["2026-09-10","Supplier transfer",-18500],["2026-09-03","Investment credit",45000],["2026-08-28","Utility bill",-3450.25],["2026-08-20","Transfer received",120000]]}};
let users=JSON.parse(localStorage.getItem("hb_users")||"null")||DEFAULT_USERS;
let blocked=JSON.parse(localStorage.getItem("hb_blocked")||"[]");
let adminPass=localStorage.getItem("hb_admin_pass")||"954&cbeweb";
const adminEmail="horizonaddis000@gmail.com";let current=null;
const $=x=>document.getElementById(x),money=n=>Number(n).toLocaleString("en-US",{minimumFractionDigits:2});
function save(){localStorage.setItem("hb_users",JSON.stringify(users));localStorage.setItem("hb_blocked",JSON.stringify(blocked));localStorage.setItem("hb_admin_pass",adminPass)}
function show(id){["login","adminLogin","create","customer","admin"].forEach(x=>$(x).classList.add("hidden"));$(id).classList.remove("hidden")}
function table(ts){return `<table class="table"><tr><th>Date</th><th>Description</th><th>Amount</th><th>Status</th></tr>${ts.map(x=>`<tr><td>${x[0]}</td><td>${x[1]}</td><td class="${x[2]>=0?"in":"out"}">${x[2]>=0?"+":"-"} ${money(Math.abs(x[2]))} Birr</td><td><span class="pill">Completed</span></td></tr>`).join("")}</table>`}
$("loginForm").onsubmit=e=>{e.preventDefault();let a=$("acct").value.trim(),u=users[a];if(u&&u.pass===$("pw").value&&!blocked.includes(a)){current={...u,key:a};show("customer");$("chip").textContent=u.name;render("dashboard")}else $("loginErr").textContent=blocked.includes(a)?"This account is blocked.":"Invalid account number or password."};
$("adminBtn").onclick=()=>show("adminLogin");$("backBtn").onclick=()=>show("login");$("createBtn").onclick=()=>show("create");$("backCreate").onclick=()=>show("login");
$("adminForm").onsubmit=e=>{e.preventDefault();if($("aemail").value.trim().toLowerCase()===adminEmail&&$("apw").value===adminPass){$("adminErr").textContent="";show("admin");renderAdmin("overview")}else $("adminErr").textContent="Invalid admin credentials."};
$("logout").onclick=()=>{current=null;show("login")};$("adminLogout").onclick=()=>show("login");
$("createForm").onsubmit=e=>{e.preventDefault();if($("npass").value!==$("nconfirm").value){$("createMsg").textContent="Passwords do not match.";return}let a="2000"+Date.now().toString().slice(-9);users[a]={pass:$("npass").value,name:$("nname").value.trim(),balance:0,email:$("nemail").value,phone:"Not provided",transactions:[]};save();$("createMsg").textContent="Account created. Your demo account number is "+a+". You can now log in.";e.target.reset()};
document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>render(b.dataset.page));document.querySelectorAll("[data-ap]").forEach(b=>b.onclick=()=>renderAdmin(b.dataset.ap));
function render(p){let u=users[current.key];$("title").textContent=p[0].toUpperCase()+p.slice(1);let c={};
c.dashboard=`<div class="grid"><div class="card balance"><div class="label">Available balance</div><div class="amount">${money(u.balance)} Birr</div><div class="label">Account •••• ${current.key.slice(-4)}</div></div><div class="card"><div class="label">Status</div><h2>Active</h2><span class="label">Demo account</span></div></div><div class="section card"><h3>Recent transactions</h3>${table(u.transactions.slice(0,5))}</div>`;
c.transactions=`<div class="card"><h3>Transaction history</h3><button class="primary" id="transferBtn">Transfer now</button><div id="transferArea" class="section hidden"><form id="transferForm" class="formgrid"><div class="info">Recipient<select id="to">${Object.entries(users).filter(([a])=>a!==current.key&&!blocked.includes(a)).map(([a,x])=>`<option value="${a}">${x.name} — ${a}</option>`).join("")}</select></div><div class="info">Amount<input id="tamount" type="number" min="1" step=".01" required></div><div class="info">Note<input id="tnote" placeholder="Optional"></div><div><button class="primary">Send transfer</button><div id="tmsg" class="label section"></div></div></form></div><div class="section">${table(u.transactions)}</div></div>`;
c.cards=`<div class="cards"><div class="bankcard"><b>HORIZON BANK</b><strong>DEMO DEBIT</strong><span>•••• •••• •••• ${current.key.slice(-4)}</span><span>${u.name.toUpperCase()}</span></div><div class="bankcard"><b>HORIZON BANK</b><strong>DEMO CREDIT</strong><span>•••• •••• •••• 2048</span><span>VALID THRU 12/29</span></div></div>`;
c.payments=`<div class="card"><h3>Utilities</h3><div class="grid">${["Electricity","Water","DSTV","Buy airtime — Safaricom","Buy airtime — Telebirr"].map(s=>`<div class="info"><b>${s}</b><p class="muted">Pay using utility account or card.</p><button class="primary pay" data-s="${s}">Make demo payment</button></div>`).join("")}</div></div>`;
c["payment-form"]=`<div class="card"><button class="link" id="backPayments">← Back to Payments</button><h3>Payment details</h3><form id="payForm" class="formgrid"><div class="info">Service<input id="service" readonly></div><div class="info">Utility account number or card number<input id="pref" required placeholder="Enter account/card number"></div><div class="info">Amount (Birr)<input id="pamount" type="number" min="1" step=".01" required placeholder="0.00"></div><div><button class="primary">Submit demo payment</button><div id="pmsg" class="label section"></div></div></form></div>`;
c.loans=`<div class="card"><h3>Loan center</h3><p class="muted">Illustrative offers based on demo account activity.</p><div class="info"><b>View demo offer</b><p>Offers use transaction-history rules, not real credit scoring.</p><button class="primary" id="offer">View demo offer</button><button class="link" id="elig">See your eligibility</button><div id="lmsg" class="label"></div></div></div>`;
c.profile=`<div class="card"><h3>Personal information</h3><div class="grid"><div class="info"><span class="label">Full name</span><br><b>${u.name}</b></div><div class="info"><span class="label">Account</span><br><b>${current.key}</b></div><div class="info"><span class="label">Phone</span><br><b>${u.phone}</b><br><button class="primary" id="phone">Change phone number</button></div><div class="info"><span class="label">Email</span><br><b>${u.email}</b><br><button class="primary" id="email">Change email</button></div></div><div class="section info"><b>Security settings</b><p>Password: ••••••••</p><button class="primary" id="changeCustomerPassword">Change password</button></div><div class="section info"><b>Active sessions</b><p>Current browser session — Active</p></div><div class="section info delete-card"><h3>Delete this account</h3><p>Before deletion, your remaining demo balance must be transferred to another destination bank/account.</p><button class="primary" id="deleteAccountBtn">Delete this account</button></div></div>`;
c["delete-account"]=`<div class="card"><button class="link" id="cancelDelete">← Back to Profile</button><h3>Delete this account</h3><p class="muted">Enter your login password and the bank/account that will receive your remaining demo balance.</p><form id="deleteForm" class="formgrid"><div class="info">Login password<input id="deletePassword" type="password" required placeholder="Enter your login password"></div><div class="info">Receiving bank<select id="receiveBank"><option>Horizon Bank</option><option>Blue Nile Bank (Demo)</option><option>Abay Bank (Demo)</option><option>Other Bank (Demo)</option></select></div><div class="info">Receiving account number<input id="receiveAccount" required placeholder="Enter receiving account number"></div><div class="info">Amount to transfer<div style="margin-top:8px;font-weight:bold">${money(u.balance)} Birr</div></div><div><button class="primary" type="submit">Confirm account deletion</button><div id="deleteMsg" class="label section"></div></div></form></div>`;
c["change-password"]=`<div class="card"><button class="link" id="backProfilePassword">← Back to Profile</button><h3>Change password</h3><form id="customerPasswordForm" class="formgrid"><div class="info">Current password<input id="customerOldPass" type="password" required></div><div class="info">New password<input id="customerNewPass" type="password" minlength="6" required></div><div class="info">Confirm new password<input id="customerNewPass2" type="password" minlength="6" required></div><div><button class="primary">Change password</button><div id="customerPassMsg" class="label section"></div></div></form></div>`;
c.notifications=`<div class="card"><h3>Notifications</h3><div class="info">Your demo account is active.</div><div class="info section">No new notifications.</div></div>`;c.support=`<div class="card"><h3>Help & Support</h3><p>This is a fictional demo. No real bank support is connected.</p></div>`;
$("content").innerHTML=c[p];
if(p==="transactions"){$("transferBtn").onclick=()=>$("transferArea").classList.toggle("hidden");$("transferForm").onsubmit=e=>{e.preventDefault();let to=users[$("to").value],n=+$("tamount").value;if(n<=0||n>u.balance){$("tmsg").textContent="Insufficient demo balance.";return}u.balance-=n;to.balance+=n;u.transactions.unshift([new Date().toISOString().slice(0,10),"Transfer to "+to.name,-n]);to.transactions.unshift([new Date().toISOString().slice(0,10),"Transfer from "+u.name,n]);save();render("transactions")}};
if(p==="payments"){document.querySelectorAll(".pay").forEach(b=>b.onclick=()=>{render("payment-form");$("service").value=b.dataset.s})}
if(p==="payment-form"){$("backPayments").onclick=()=>render("payments");$("payForm").onsubmit=e=>{e.preventDefault();let n=+$("pamount").value;if(n<=0){$("pmsg").textContent="Enter a valid amount.";return}if(n>u.balance){$("pmsg").textContent="Insufficient demo balance.";return}u.balance-=n;u.transactions.unshift([new Date().toISOString().slice(0,10),$("service").value+" — "+$("pref").value,-n]);save();$("pmsg").textContent="Demo payment completed.";setTimeout(()=>render("payments"),500)}}
if(p==="loans"){$("offer").onclick=()=>{$("lmsg").textContent=u.transactions.length>=5?"Eligible: illustrative offer up to "+money(Math.min(150000,u.balance*.25))+" Birr.":"No offer yet. Complete more demo transactions.";};$("elig").onclick=()=>{$("lmsg").textContent=u.transactions.length>=3?"Eligibility: starter demo offer available.":"Eligibility: not eligible yet.";}}
if(p==="profile"){$("phone").onclick=()=>{let v=prompt("New demo phone number",u.phone);if(v){u.phone=v;save();render("profile")}};$("email").onclick=()=>{let v=prompt("New demo email",u.email);if(v){u.email=v;save();render("profile")}};$("changeCustomerPassword").onclick=()=>render("change-password");$("deleteAccountBtn").onclick=()=>render("delete-account")}}
if(p==="delete-account"){$("cancelDelete").onclick=()=>render("profile");$("deleteForm").onsubmit=e=>{e.preventDefault();let msg=$("deleteMsg"),pw=$("deletePassword").value,bank=$("receiveBank").value,acct=$("receiveAccount").value.trim();if(pw!==u.pass){msg.textContent="The login password is incorrect.";return}if(!acct){msg.textContent="Enter the receiving account number.";return}let amount=Number(u.balance||0);if(amount>0){u.transactions=u.transactions||[];u.transactions.unshift([new Date().toISOString().slice(0,10),"Account closure transfer to "+bank+" / "+acct,-amount])}delete users[current.key];save();msg.textContent="Account deleted and "+money(amount)+" Birr was assigned to "+bank+" account "+acct+" in this demo.";setTimeout(()=>{current=null;show("login")},900)}}
if(p==="change-password"){$("backProfilePassword").onclick=()=>render("profile");$("customerPasswordForm").onsubmit=e=>{e.preventDefault();let msg=$("customerPassMsg"),old=$("customerOldPass").value,n1=$("customerNewPass").value,n2=$("customerNewPass2").value;if(old!==u.pass){msg.textContent="Current password is incorrect.";return}if(n1!==n2){msg.textContent="Passwords do not match.";return}if(n1.length<6){msg.textContent="Password must be at least 6 characters.";return}u.pass=n1;save();msg.textContent="Password changed successfully.";e.target.reset()}}
function renderAdmin(p){$("atitle").textContent=p[0].toUpperCase()+p.slice(1);let entries=Object.entries(users);let c={};
c.overview=`<div class="admincards">${entries.map(([a,u])=>`<div class="card"><div class="label">${u.name}</div><h2>${money(u.balance)}</h2><span class="label">Birr</span></div>`).join("")}</div><div class="section card"><b>System status</b><p>Demo services operational · ${entries.length} customers · ${blocked.length} blocked</p></div>`;
c.customers=`<div class="card"><h3>Customer accounts</h3>${entries.map(([a,u])=>`<div class="info section"><b>${u.name}</b><br>${a}<br>Balance: ${money(u.balance)} Birr</div>`).join("")}</div>`;
c.transactions=`<div class="card"><h3>All customer transactions</h3>${table(entries.flatMap(([a,u])=>u.transactions.map(x=>[x[0],u.name+" — "+x[1],x[2]])))}</div>`;
c.payments=`<div class="card"><h3>Payment operations</h3><div class="info">Demo payment monitoring is enabled.</div></div>`;
c.security=`<div class="card"><h3>Security & Alerts</h3><div class="info">Login monitoring: enabled · Audit logging: enabled</div><div class="section"><h3>Block users</h3>${entries.map(([a,u])=>`<div class="info section"><b>${u.name}</b> — ${a}<br><button class="primary block" data-a="${a}">${blocked.includes(a)?"Unblock":"Block"} user</button></div>`).join("")}</div><div class="section"><h3>Change administrator password</h3><form id="changeAdmin" class="formgrid"><div class="info">Current password<input id="oldpass" type="password" required></div><div class="info">New password<input id="newadmin" type="password" minlength="6" required></div><div class="info">Confirm<input id="newadmin2" type="password" minlength="6" required></div><div><button class="primary">Change password</button><div id="adminPassMsg" class="label section"></div></div></form></div></div>`;
c.settings=`<div class="card"><h3>System Settings</h3><div class="info">Demo mode: ON</div><div class="info section">Session timeout: simulated</div></div>`;c.audit=`<div class="card"><h3>Audit Log</h3><div class="info">Admin console opened</div><div class="info section">Customer records reviewed</div><div class="info section">Security controls available</div></div>`;
$("acontent").innerHTML=c[p];
if(p==="security"){$("changeAdmin").onsubmit=e=>{e.preventDefault();let msg=$("adminPassMsg");if($("oldpass").value!==adminPass){msg.textContent="Current password is incorrect.";return}if($("newadmin").value!==$("newadmin2").value){msg.textContent="Passwords do not match.";return}adminPass=$("newadmin").value;save();msg.textContent="Admin password changed successfully.";e.target.reset()};document.querySelectorAll(".block").forEach(b=>b.onclick=()=>{let a=b.dataset.a;blocked.includes(a)?blocked=blocked.filter(x=>x!==a):blocked.push(a);save();renderAdmin("security")})}}
render("dashboard");

function applyTheme(theme){
  theme=theme==="dark"?"dark":"light";
  document.body.classList.remove("theme-dark","theme-light");
  document.body.classList.add(theme==="dark"?"theme-dark":"theme-light");
  localStorage.setItem("hb_theme",theme);
  document.querySelectorAll(".theme-option").forEach(b=>{
    b.classList.toggle("active",b.dataset.themeChoice===theme);
  });
}
document.addEventListener("click",e=>{
  const b=e.target.closest(".theme-option");
  if(b) applyTheme(b.dataset.themeChoice);
});
applyTheme(localStorage.getItem("hb_theme")||"light");
